---
title: "code book of Getting and cleanning data Assignment"
author: "Yangtaoyuan"
date: "2020/11/17"
output:
  pdf_document: default
  html_document: default
---
There is the code book of the Getting and cleanning data project assignment.
---
1.1 read downloaded file 
------
```{r}
setwd("C:/Users/Administrator/Desktop/coursea/getting_and_cleaning_data/week4/Getting-Cleanning-Project-Assignment/getdata_projectfiles_UCI HAR Dataset/UCI HAR Dataset")
library(plyr)
library(data.table)
subjectTrain = read.table('./train/subject_train.txt',header=FALSE)
xTrain = read.table('./train/x_train.txt',header=FALSE)
yTrain = read.table('./train/y_train.txt',header=FALSE)

subjectTest = read.table('./test/subject_test.txt',header=FALSE)
xTest = read.table('./test/x_test.txt',header=FALSE)
yTest = read.table('./test/y_test.txt',header=FALSE)
```
1.2 Merges the training and testing sets into one dataset called "subjectDataset"
-------
```{r}

xDataSet <- rbind(xTrain, xTest)
yDataSet <- rbind(yTrain, yTest)
subjectDataSet <- rbind(subjectTrain, subjectTest)
dim(xDataSet)
dim(yDataSet)
dim(subjectDataSet)
```
2. Extracts only the measurements on the mean and standard deviation for each measurement.
--------
```{r}
xDataSet_mean_std <- xDataSet[, grep("-(mean|std)\\(\\)", read.table("features.txt")[, 2])]
names(xDataSet_mean_std) <- read.table("features.txt")[grep("-(mean|std)\\(\\)", read.table("features.txt")[, 2]), 2]
View(xDataSet_mean_std)
dim(xDataSet_mean_std)
```

3. Uses descriptive activity names to name the activities in the data set
---------
```{r}
yDataSet[, 1] <- read.table("activity_labels.txt")[yDataSet[, 1], 2]
names(yDataSet) <- "Activity"
View(yDataSet)

```
4. Appropriately labels the data set with descriptive variable names.
---------
```{r}

names(subjectDataSet) <- "Subject"
summary(subjectDataSet)

singleDataSet <- cbind(xDataSet_mean_std, yDataSet, subjectDataSet)

# Defining descriptive names for all variables.

names(singleDataSet) <- make.names(names(singleDataSet))
names(singleDataSet) <- gsub('Acc',"Acceleration",names(singleDataSet))
names(singleDataSet) <- gsub('GyroJerk',"AngularAcceleration",names(singleDataSet))
names(singleDataSet) <- gsub('Gyro',"AngularSpeed",names(singleDataSet))
names(singleDataSet) <- gsub('Mag',"Magnitude",names(singleDataSet))
names(singleDataSet) <- gsub('^t',"TimeDomain.",names(singleDataSet))
names(singleDataSet) <- gsub('^f',"FrequencyDomain.",names(singleDataSet))
names(singleDataSet) <- gsub('\\.mean',".Mean",names(singleDataSet))
names(singleDataSet) <- gsub('\\.std',".StandardDeviation",names(singleDataSet))
names(singleDataSet) <- gsub('Freq\\.',"Frequency.",names(singleDataSet))
names(singleDataSet) <- gsub('Freq$',"Frequency",names(singleDataSet))

View(singleDataSet)


```

5. From the data set in step 4, creates a  second, independent tidy data set with the average of each variable for each activity and each subject.  the data as output as tidydata.txt
------
```{r}
names(singleDataSet)

Data2<-aggregate(. ~Subject + Activity, singleDataSet, mean)
Data2<-Data2[order(Data2$Subject,Data2$Activity),]
write.table(Data2, file = "tidydata.txt",row.name=FALSE)
```

